version: "3.7"

services:
    web:
        build:
            context: ../dev
            dockerfile: Dockerfile
        ports:
            - "3535:80"
        volumes:
            - ..:/var/www/html
        tty: true
        stdin_open: true

    playwright:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/usr/app
        tty: true
        stdin_open: true
    